[package]
name = "tmdb-easy"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
reqwest = { version = "0.13.1", features = ["blocking"] }
tmdb-easy-raw = { version = "0.1.0", path = "../tmdb-easy-raw", features = [
    "blocking",
] }
